name: Build and Validate CyberBotChat

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET 8 SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build in Release mode
      run: dotnet build --configuration Release --no-restore

    - name: Run unit tests (if any)
      run: dotnet test --no-build --verbosity normal
      continue-on-error: true

    - name: Code style check
      run: dotnet format --verify-no-changes --verbosity diagnostic
      continue-on-error: true
